"""
Django URL Configuration for Your Project.

This module defines the URL configuration for your Django project, specifying the URL patterns and their associated views.

URL Patterns:
- '/admin/': Provides access to the Django admin interface.
- '/api/docs/schema/': Exposes the raw schema generated by Spectacular.
- '/api/docs/schema/ui/': Presents the API schema using Spectacular's Swagger UI.
- '/': Includes the API endpoints generated by the DefaultRouter in 'router'.

API Endpoints:
- '/api/server/select/': Provides API endpoints for retrieving and filtering server objects.

Additionally, the configuration includes temporary login and logout endpoints for the Django REST framework.

The 'SpectacularAPIView' and 'SpectacularSwaggerView' views are used for generating API documentation with Spectacular.

Attributes:
- 'router': A DefaultRouter for registering API viewsets.

URL Configuration and ViewSets:
- 'ServerListViewSet': A viewset for retrieving and filtering a list of server objects.

Usage:
This URL configuration connects your project's views and viewsets to specific URL patterns, making your API and
admin interface accessible through well-defined URLs.
"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView 
from rest_framework.routers import DefaultRouter
from server.views import ServerListViewSet

router = DefaultRouter()
router.register('api/server/select', ServerListViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/docs/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/docs/schema/ui/', SpectacularSwaggerView.as_view(), name="swagger-api-docs"),
    path('', include(router.urls)),

    # temporary login-logout
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

